// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BroadcastMessageBroadcastPostData, BroadcastMessageBroadcastPostErrors, BroadcastMessageBroadcastPostResponses, CheckHealthHealthGetData, CheckHealthHealthGetResponses, CreateUserUsersPostData, CreateUserUsersPostErrors, CreateUserUsersPostResponses, GetActiveChannelsBroadcastChannelsGetData, GetActiveChannelsBroadcastChannelsGetResponses, GetUsersUsersGetData, GetUsersUsersGetErrors, GetUsersUsersGetResponses, GetUserUsersUserIdGetData, GetUserUsersUserIdGetErrors, GetUserUsersUserIdGetResponses, RootGetData, RootGetResponses, TestDbConnectionUsersDbTestGetData, TestDbConnectionUsersDbTestGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Test Db Connection
 *
 * Test database connection
 */
export const testDbConnectionUsersDbTestGet = <ThrowOnError extends boolean = false>(options?: Options<TestDbConnectionUsersDbTestGetData, ThrowOnError>) => (options?.client ?? client).get<TestDbConnectionUsersDbTestGetResponses, unknown, ThrowOnError>({ url: '/users/db-test', ...options });

/**
 * Get Users
 *
 * Get all users
 */
export const getUsersUsersGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersUsersGetData, ThrowOnError>) => (options?.client ?? client).get<GetUsersUsersGetResponses, GetUsersUsersGetErrors, ThrowOnError>({ url: '/users/', ...options });

/**
 * Create User
 *
 * Create a new user
 */
export const createUserUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserUsersPostResponses, CreateUserUsersPostErrors, ThrowOnError>({
    url: '/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get User
 *
 * Get a user by ID
 */
export const getUserUsersUserIdGet = <ThrowOnError extends boolean = false>(options: Options<GetUserUsersUserIdGetData, ThrowOnError>) => (options.client ?? client).get<GetUserUsersUserIdGetResponses, GetUserUsersUserIdGetErrors, ThrowOnError>({ url: '/users/{user_id}', ...options });

/**
 * Broadcast Message
 *
 * Broadcast a message to all WebSocket clients in a channel.
 *
 * This is useful for server-side events that need to push updates
 * to connected clients (e.g., notifications, alerts, system updates).
 *
 * Example:
 * ```json
 * {
 * "channel": "general",
 * "message": {
 * "title": "Server Update",
 * "content": "Server maintenance in 10 minutes",
 * "priority": "high"
 * }
 * }
 * ```
 */
export const broadcastMessageBroadcastPost = <ThrowOnError extends boolean = false>(options: Options<BroadcastMessageBroadcastPostData, ThrowOnError>) => (options.client ?? client).post<BroadcastMessageBroadcastPostResponses, BroadcastMessageBroadcastPostErrors, ThrowOnError>({
    url: '/broadcast/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Active Channels
 *
 * Get list of active channels and connection counts
 */
export const getActiveChannelsBroadcastChannelsGet = <ThrowOnError extends boolean = false>(options?: Options<GetActiveChannelsBroadcastChannelsGetData, ThrowOnError>) => (options?.client ?? client).get<GetActiveChannelsBroadcastChannelsGetResponses, unknown, ThrowOnError>({ url: '/broadcast/channels', ...options });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Check Health
 */
export const checkHealthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<CheckHealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<CheckHealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
