// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BroadcastMessage
 */
export type BroadcastMessage = {
    /**
     * Channel
     */
    channel: string;
    /**
     * Message
     */
    message: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type TestDbConnectionUsersDbTestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/db-test';
};

export type TestDbConnectionUsersDbTestGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/users/';
};

export type GetUsersUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersUsersGetError = GetUsersUsersGetErrors[keyof GetUsersUsersGetErrors];

export type GetUsersUsersGetResponses = {
    /**
     * Response Get Users Users  Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetUsersUsersGetResponse = GetUsersUsersGetResponses[keyof GetUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type GetUserUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUsersUserIdGetError = GetUserUsersUserIdGetErrors[keyof GetUserUsersUserIdGetErrors];

export type GetUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserUsersUserIdGetResponse = GetUserUsersUserIdGetResponses[keyof GetUserUsersUserIdGetResponses];

export type BroadcastMessageBroadcastPostData = {
    body: BroadcastMessage;
    path?: never;
    query?: never;
    url: '/broadcast/';
};

export type BroadcastMessageBroadcastPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BroadcastMessageBroadcastPostError = BroadcastMessageBroadcastPostErrors[keyof BroadcastMessageBroadcastPostErrors];

export type BroadcastMessageBroadcastPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetActiveChannelsBroadcastChannelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/broadcast/channels';
};

export type GetActiveChannelsBroadcastChannelsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckHealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type CheckHealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
